version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Athens'
      WEBPASSWORD: 'pihole'
    volumes:
      - '/root/etc-pihole:/etc/pihole'
      - '/root/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
