version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: 1000:1000
    #user: 0:0
    network_mode: 'host'
    volumes:
      - /root/jellyfin/config:/config
      - /root/jellyfin/cache:/cache
      - /srv/dev-disk-by-uuid-0098ad2b-2b47-4904-802e-aeefb3a7af88/media:/media
    restart: 'unless-stopped'
