version: "2.1"
services:
  transmission:
    image: jaymoulin/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME=/flood-for-transmission
      #- USER= #optional
      #- PASS= #optional
      #- WHITELIST= #optional
      #- PEERPORT= #optional
      #- HOST_WHITELIST= #optional
    volumes:
      - /root/transmission/config:/config
      - /srv/dev-disk-by-uuid-0098ad2b-2b47-4904-802e-aeefb3a7af88/media:/downloads
      - /root/mediaServerInstallScripts/transmission/flood-for-transmission:/flood-for-transmission
      #- /path/to/watch/folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
